# Generated by Django 5.2 on 2025-05-21 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0014_person_unread_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='availability',
            field=models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Borrowed', 'Borrowed'), ('Deleted', 'Deleted')], default='Available', max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='book_covers/default_book_cover.png', null=True, upload_to='book_covers/'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 6, 5)),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2025, 5, 23)),
        ),
    ]
