# Generated by Django 5.2 on 2025-05-24 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0015_alter_book_availability_alter_book_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 6, 8)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2025, 5, 26)),
        ),
    ]
