# Generated by Django 5.2 on 2025-05-24 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0016_event_status_alter_borrow_due_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_canceled',
            new_name='is_cancelled',
        ),
    ]
