# Generated by Django 5.2 on 2025-05-25 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0017_rename_is_canceled_event_is_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 6, 9)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2025, 5, 28)),
        ),
    ]
