# Generated by Django 5.2 on 2025-05-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0018_alter_borrow_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/profile_pic1.png', null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
